server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://192.168.8.111/springboot_jpa
    username: root
    password: 1qaz!QAZ
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

